[build]
  command = "npm run build"
  publish = "dist/NeuroApp/browser"

[[redirects]]
  from = "/api/*"
  to = "http://82.29.190.91:5000/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
